travis:
  secure:
    BINSTAR_TOKEN: pCWLpvDyvGA6yNRBYHnllSOaD3zbbA2P4uPgHc0/QM8EbccwukyOmU5OZIop4TlT1Gd2gAzJKcaHoq9fFWEE7wC6xM6IMTQio9eLqyxuAYtd9F1yCgMOJVIB254ycBTGEpPCh/sZ+ds2hbcpGuyODxZU3z9di8IFNCUpxTWeEWU2yQzcijOc9ao625itiBaR9e3+CM/K7QC17uXxnvkL/DD5v312uqf+KgnoeePAi6ldmyG3tqghhV/CoUZgNh/I/A07a9a1qivOTUIudOniPyYGKSzylVwtv9tPuMSyJdzBmMTKM5eHOYoQdykVhT7L/V7x40mnL+McnnP3KwxXsWrLG9ad8V8oN7EH44Lj1NWM8xkctUNjoqdJ6TvzvNs33LF5YE3G+BG/Us7R5OXNPVojRrgDM3zhgjOBB1QlhcmD/U+YNz29DDoFmhYJDyAL1EAYBdqkN+rQgXx0uhivMvEHmEY5loca0rdyp9K8Tc9PchY0mNLR0vByv2i3jSk6Qk37ir0YVAedqWYQbIvFTmOkGJpv7xYF4TumfMsKxqW8i+SZKQtKKcAR3iuBQ9Ix91G+J1UIyWXwOVqbOf5b86wACZCoKlLgT/9XU1FRNZdRTfmFxiU91F2hHTLGwk3G+qnSRMQEni/WSADaHDrWWCGwrJeuHo6LWF6oQTt9iCI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
